import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { auth } from "@/auth";
import QueryProvider from "@/components/QueryProvider"; // Import the provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Linkbird Replica",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <QueryProvider> {/* Add the provider here */}
          <div className="flex min-h-screen bg-gray-100/50">
            {/* This will only show the Sidebar if the user is logged in */}
            {session?.user && <Sidebar />}
            <main className="flex-1 w-full">{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}

